print("AAA"); print("BBB")
print("CCC")
print("DDD\nEEE\nFFF")
print("DDD\tEEE\tFFF")
#............................
print('welcome "SAU"')
print("welcome \"SAU\"")
#............................
print("welcome 'Iot'")
print('welcome \'Iot\'')
print('ABC\\DEF')
#............................
Print('''                     
        SAU....
        Iot....
        Wow....
        Hi...
        ''')